language: node_js
node_js:
  - 18.16.0
cache:
  directories:
    - node_modules
env:
  - CI=true
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  local-dir: dist
  github_token: $github_token
  on:
    branch: main
